//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldTypes
    {
        public FieldTypes()
        {
            this.FieldTypeValues = new HashSet<FieldTypeValues>();
            this.SealFields = new HashSet<SealFields>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<FieldTypeValues> FieldTypeValues { get; set; }
        public virtual ICollection<SealFields> SealFields { get; set; }
    }
}
