//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldTypeValues
    {
        public FieldTypeValues()
        {
            this.FieldTypeValues1 = new HashSet<FieldTypeValues>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid FieldTypeId { get; set; }
        public string Value { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    
        public virtual FieldTypes FieldTypes { get; set; }
        public virtual ICollection<FieldTypeValues> FieldTypeValues1 { get; set; }
        public virtual FieldTypeValues FieldTypeValues2 { get; set; }
    }
}
