//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MLGTEntities : DbContext
    {
        public MLGTEntities()
            : base("name=MLGTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campaigns> Campaigns { get; set; }
        public DbSet<FieldTypes> FieldTypes { get; set; }
        public DbSet<FieldTypeValues> FieldTypeValues { get; set; }
        public DbSet<SealFields> SealFields { get; set; }
        public DbSet<Seals> Seals { get; set; }
        public DbSet<SealScenario> SealScenario { get; set; }
        public DbSet<SealStatistic> SealStatistic { get; set; }
        public DbSet<StatisticMetrics> StatisticMetrics { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Templates> Templates { get; set; }
    }
}
