//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SealScenario
    {
        public System.Guid Id { get; set; }
        public System.Guid SealId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual Seals Seals { get; set; }
    }
}
