//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seals
    {
        public Seals()
        {
            this.Campaigns = new HashSet<Campaigns>();
            this.SealFields = new HashSet<SealFields>();
            this.SealScenario = new HashSet<SealScenario>();
            this.SealStatistic = new HashSet<SealStatistic>();
        }
    
        public System.Guid Id { get; set; }
        public string ClientName { get; set; }
        public string WebsiteURL { get; set; }
        public string ClientEmailAddress { get; set; }
        public System.Guid TemplateId { get; set; }
        public string ClientEmailBody { get; set; }
        public string UserEmailBody { get; set; }
    
        public virtual ICollection<Campaigns> Campaigns { get; set; }
        public virtual ICollection<SealFields> SealFields { get; set; }
        public virtual Templates Templates { get; set; }
        public virtual ICollection<SealScenario> SealScenario { get; set; }
        public virtual ICollection<SealStatistic> SealStatistic { get; set; }
    }
}
