//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticMetrics
    {
        public StatisticMetrics()
        {
            this.SealStatistic = new HashSet<SealStatistic>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SealStatistic> SealStatistic { get; set; }
    }
}
