//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGo.MLGT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templates
    {
        public Templates()
        {
            this.Seals = new HashSet<Seals>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Template { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual ICollection<Seals> Seals { get; set; }
    }
}
